'use client';
import React, { useState, useEffect, useRef } from 'react';
import { Minus, Plus, ChevronLeft, ChevronRight } from 'lucide-react';
import { ExtractedQuestion } from '@/types';
import { BoundingBoxOverlay } from './BoundingBoxOverlay';

interface PDFAnswerViewerProps {
  questions: ExtractedQuestion[];
  activeQuestionId: string;
  currentPage: number;
  totalPages: number;
  onPageChange: (p: number) => void;
  onSelectQuestion: (id: string) => void;
  answerSheetFiles?: File[];
}

/** Auto-crop pure white/near-white A4 page margin strips generated by PDF creation apps */
function autoCropWhitePdfMargins(canvas: HTMLCanvasElement): HTMLCanvasElement {
  const ctx = canvas.getContext('2d');
  if (!ctx) return canvas;

  const w = canvas.width;
  const h = canvas.height;
  const imgData = ctx.getImageData(0, 0, w, h);
  const data = imgData.data;

  // Check if pixel is white or near-white (R >= 240, G >= 240, B >= 240)
  const isWhitePixel = (x: number, y: number) => {
    const i = (y * w + x) * 4;
    return data[i] >= 240 && data[i + 1] >= 240 && data[i + 2] >= 240;
  };

  // Find top white margin
  let top = 0;
  for (let y = 0; y < h * 0.35; y++) {
    let whiteCount = 0;
    for (let x = 0; x < w; x++) {
      if (isWhitePixel(x, y)) whiteCount++;
    }
    if (whiteCount / w > 0.92) {
      top = y + 1;
    } else {
      break;
    }
  }

  // Find bottom white margin
  let bottom = h - 1;
  for (let y = h - 1; y > h * 0.65; y--) {
    let whiteCount = 0;
    for (let x = 0; x < w; x++) {
      if (isWhitePixel(x, y)) whiteCount++;
    }
    if (whiteCount / w > 0.92) {
      bottom = y - 1;
    } else {
      break;
    }
  }

  // Find left white margin
  let left = 0;
  for (let x = 0; x < w * 0.35; x++) {
    let whiteCount = 0;
    const colHeight = bottom - top + 1;
    for (let y = top; y <= bottom; y++) {
      if (isWhitePixel(x, y)) whiteCount++;
    }
    if (colHeight > 0 && whiteCount / colHeight > 0.92) {
      left = x + 1;
    } else {
      break;
    }
  }

  // Find right white margin
  let right = w - 1;
  for (let x = w - 1; x > w * 0.65; x--) {
    let whiteCount = 0;
    const colHeight = bottom - top + 1;
    for (let y = top; y <= bottom; y++) {
      if (isWhitePixel(x, y)) whiteCount++;
    }
    if (colHeight > 0 && whiteCount / colHeight > 0.92) {
      right = x - 1;
    } else {
      break;
    }
  }

  const cropW = right - left + 1;
  const cropH = bottom - top + 1;

  if (cropW > 100 && cropH > 100 && (left > 0 || right < w - 1 || top > 0 || bottom < h - 1)) {
    const cropped = document.createElement('canvas');
    cropped.width = cropW;
    cropped.height = cropH;
    const croppedCtx = cropped.getContext('2d');
    if (croppedCtx) {
      croppedCtx.drawImage(canvas, left, top, cropW, cropH, 0, 0, cropW, cropH);
      return cropped;
    }
  }

  return canvas;
}

/** Render a single PDF page into a canvas using PDF.js and return a data-URL with exact total pages */
async function renderPdfPageToDataUrl(file: File, pageNum: number): Promise<{ dataUrl: string; numPages: number }> {
  // Dynamic import PDF.js only client-side
  const pdfjsLib = await import('pdfjs-dist');
  // Set worker — use CDN to avoid bundler issues with .mjs workers
  pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;

  const arrayBuffer = await file.arrayBuffer();
  const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
  const pdf = await loadingTask.promise;

  const numPages = pdf.numPages;
  const safePage = Math.min(Math.max(pageNum, 1), numPages);
  const page = await pdf.getPage(safePage);

  const scale = 2.0; // 2× for sharp high-dpi rendering
  const viewport = page.getViewport({ scale });

  const canvas = document.createElement('canvas');
  canvas.width = viewport.width;
  canvas.height = viewport.height;

  const ctx = canvas.getContext('2d')!;
  await page.render({ canvasContext: ctx, canvas, viewport } as any).promise;

  // Automatically trim pure white/near-white A4 PDF page margins
  const trimmedCanvas = autoCropWhitePdfMargins(canvas);

  return {
    dataUrl: trimmedCanvas.toDataURL('image/png'),
    numPages,
  };
}

export const PDFAnswerViewer: React.FC<PDFAnswerViewerProps> = ({
  questions, activeQuestionId, currentPage, totalPages, onPageChange, onSelectQuestion, answerSheetFiles,
}) => {
  const [zoom, setZoom] = useState(100);

  // For image files: blob URL entries
  const [fileEntries, setFileEntries] = useState<{ url: string; isPDF: boolean }[]>([]);

  // For PDF files: rendered page data-URL cache and exact total pages
  const [pdfPageDataUrl, setPdfPageDataUrl] = useState<string | null>(null);
  const [pdfTotalPages, setPdfTotalPages] = useState<number | null>(null);
  const [pdfRendering, setPdfRendering] = useState(false);

  // Track whether uploaded files are a single PDF
  const isPDFUpload = answerSheetFiles?.length === 1 &&
    (answerSheetFiles[0].type === 'application/pdf' || answerSheetFiles[0].name.toLowerCase().endsWith('.pdf'));

  // Build blob URL entries for image-based uploads
  useEffect(() => {
    if (!answerSheetFiles || answerSheetFiles.length === 0) {
      setFileEntries([]);
      return;
    }
    if (isPDFUpload) {
      setFileEntries([]); // Not needed for PDF canvas path
      return;
    }
    const entries = answerSheetFiles.map((f) => ({
      url: URL.createObjectURL(f),
      isPDF: false,
    }));
    setFileEntries(entries);
    return () => { entries.forEach((e) => URL.revokeObjectURL(e.url)); };
  }, [answerSheetFiles, isPDFUpload]);

  // Render PDF page to canvas data-URL whenever PDF file or page changes
  useEffect(() => {
    if (!isPDFUpload || !answerSheetFiles || answerSheetFiles.length === 0) return;
    let cancelled = false;
    setPdfRendering(true);
    setPdfPageDataUrl(null);

    renderPdfPageToDataUrl(answerSheetFiles[0], currentPage)
      .then(({ dataUrl, numPages }) => {
        if (!cancelled) {
          setPdfPageDataUrl(dataUrl);
          setPdfTotalPages(numPages);
          setPdfRendering(false);
        }
      })
      .catch((err) => {
        console.error('PDF.js render error:', err);
        if (!cancelled) setPdfRendering(false);
      });

    return () => { cancelled = true; };
  }, [answerSheetFiles, currentPage, isPDFUpload]);

  // Determine effective total pages: use actual PDF numPages if available
  const effectiveTotalPages = isPDFUpload
    ? (pdfTotalPages || 1)
    : (answerSheetFiles && answerSheetFiles.length > 0 ? answerSheetFiles.length : (totalPages || 1));

  // Current image entry for image-based uploads
  const isMultipleFiles = fileEntries.length > 1;
  const currentEntry = isMultipleFiles
    ? fileEntries[currentPage - 1] || fileEntries[0]
    : fileEntries[0];

  // Determine what image URL to show
  const displayUrl = isPDFUpload ? pdfPageDataUrl : (currentEntry?.url ?? null);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        minHeight: 0,
        backgroundColor: '#28282E',
        borderRadius: '24px',
        overflow: 'hidden',
      }}
    >
      {/* ── Top Toolbar ── */}
      <div style={{
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
        padding: '12px 20px',
        borderBottom: '1px solid rgba(255,255,255,0.10)',
      }}>
        <span style={{
          fontSize: '14px',
          fontWeight: 700,
          color: 'rgba(255,255,255,0.90)',
          flex: '1 1 0%',
          minWidth: 0,
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        }}>Answer Sheet</span>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexShrink: 0 }}>
          {/* Zoom control */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: '6px',
            backgroundColor: 'rgba(255,255,255,0.10)', borderRadius: '10px', padding: '6px 10px',
          }}>
            <button onClick={() => setZoom(v => Math.max(v - 15, 50))}
              style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.70)', cursor: 'pointer', padding: 0, display: 'flex' }}>
              <Minus size={13} strokeWidth={2} />
            </button>
            <span style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255,255,255,0.90)', minWidth: '36px', textAlign: 'center', whiteSpace: 'nowrap' }}>
              {zoom}%
            </span>
            <button onClick={() => setZoom(v => Math.min(v + 15, 200))}
              style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.70)', cursor: 'pointer', padding: 0, display: 'flex' }}>
              <Plus size={13} strokeWidth={2} />
            </button>
          </div>

          {/* Page navigation */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: '6px',
            backgroundColor: 'rgba(255,255,255,0.10)', borderRadius: '10px', padding: '6px 10px',
          }}>
            <button
              onClick={() => onPageChange(Math.max(currentPage - 1, 1))}
              disabled={currentPage <= 1}
              style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.70)', cursor: 'pointer', padding: 0, display: 'flex', opacity: currentPage <= 1 ? 0.3 : 1 }}>
              <ChevronLeft size={14} strokeWidth={2} />
            </button>
            <span style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255,255,255,0.90)', whiteSpace: 'nowrap' }}>
              Page {currentPage} of {effectiveTotalPages}
            </span>
            <button
              onClick={() => onPageChange(Math.min(currentPage + 1, effectiveTotalPages))}
              disabled={currentPage >= effectiveTotalPages}
              style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,0.70)', cursor: 'pointer', padding: 0, display: 'flex', opacity: currentPage >= effectiveTotalPages ? 0.3 : 1 }}>
              <ChevronRight size={14} strokeWidth={2} />
            </button>
          </div>
        </div>
      </div>

      {/* ── Document Canvas: Dark bg, NO scrollbar, NO white box ── */}
      <div
        style={{
          flex: '1 1 0%',
          minHeight: 0,
          overflow: 'hidden',   /* ← HARD HIDDEN — no scrollbar will ever appear */
          padding: '16px',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#1E1E24',
        }}
      >
        {/* Inner wrapper: transparent bg, shadow, relative for overlay */}
        <div
          style={{
            position: 'relative',
            width: '100%',
            maxWidth: 520,
            height: '100%',
            maxHeight: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            transform: `scale(${zoom / 100})`,
            transformOrigin: 'center center',
            transition: 'transform 0.2s',
            /* transparent — the paper image provides its own white background */
            backgroundColor: 'transparent',
          }}
        >
          {pdfRendering && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', color: 'rgba(255,255,255,0.5)' }}>
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
                style={{ animation: 'spin 1s linear infinite' }}>
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
              <span style={{ fontSize: '13px', fontWeight: 500 }}>Rendering page {currentPage}…</span>
            </div>
          )}

          {!pdfRendering && displayUrl && (
            <div
              style={{
                position: 'relative',
                display: 'inline-block',
                maxWidth: '100%',
                maxHeight: '100%',
                lineHeight: 0,
              }}
            >
              <img
                src={displayUrl}
                alt={`Answer Sheet Page ${currentPage}`}
                style={{
                  maxWidth: '100%',
                  maxHeight: '100%',
                  objectFit: 'contain',
                  borderRadius: '8px',
                  boxShadow: '0 25px 60px rgba(0,0,0,0.4)',
                  display: 'block',
                }}
              />
              {/* Bounding box overlay positioned precisely over the image */}
              <BoundingBoxOverlay
                questions={questions}
                activeQuestionId={activeQuestionId}
                currentPage={currentPage}
                onSelectQuestion={onSelectQuestion}
              />
            </div>
          )}

          {!pdfRendering && !displayUrl && (
            <div style={{ color: 'rgba(255,255,255,0.35)', textAlign: 'center' }}>
              <p style={{ fontSize: '13px', fontWeight: 500 }}>Answer Sheet Page {currentPage}</p>
            </div>
          )}
        </div>
      </div>

      <style>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
};
